import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Area, Bar, BarChart, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Activity, ArrowDownToLine, ArrowUpRight, ChevronLeft, ZoomIn, ZoomOut, CalendarDays, Check, ChevronRight, CircleHelp, Clock3, Database, Droplets, Gauge, History, LayoutDashboard, RefreshCw, Settings2, ShieldCheck, Thermometer, Waves, Wind } from 'lucide-react'
import { SystemSettings } from './SystemSettings'
import './style.css'

type Metric = 'pm25'|'aqi'|'temperature'|'humidex'
type Point = {ts:number,temperature:number|null,humidity:number|null,pm25:number|null,aqi:number|null,samples:number,pm_min:number|null,pm_max:number|null,flagged:number,above_threshold?:boolean}
type Forecast={valid:number,fetched:number,kind:string,temperature:number|null,humidity:number|null,pm25:number|null,aqi?:number|null,uv_index:number|null,precipitation_probability:number|null}
type Reading={ts:number,temperature:number|null,humidity:number|null,pm25:number|null,aqi:number|null,pm_a:number|null,pm_b:number|null,method:string,quality:string,beyond_scale:boolean,temperature_raw:number|null,humidity_raw:number|null,environment_mode:string}
type Latest={reading:Reading|null,nowcast_aqi:number|null,nowcast_pm25:number|null,nowcast_beyond_scale:boolean,stale:boolean,server_time:number}
type Stats={samples:number,temp_min:number|null,temp_max:number|null,temp_mean:number|null,humidity_mean:number|null,pm_mean:number|null,pm_max:number|null,pm_min:number|null}
type HistoryData={points:Point[],forecasts:Forecast[],step:number,stats:Stats}
type Status={version:string,jobs:{name:string,last_attempt:number|null,last_success:number|null,error:string|null}[],readings:{n:number,first:number|null,last:number|null},database_bytes:number,timezone:string,backup_scope:string}
const metrics:Record<Metric,{title:string,unit:string,color:string,icon:typeof Wind}>={pm25:{title:'Fine particles',unit:'µg/m³',color:'#70d8c2',icon:Wind},aqi:{title:'US AQI',unit:'AQI',color:'#b0a2ff',icon:Gauge},temperature:{title:'Temperature',unit:'°F',color:'#f1b686',icon:Thermometer},humidex:{title:'Estimated Humidex',unit:'°F',color:'#8db8f9',icon:Droplets}}
const ranges=[{label:'1 hour',seconds:3600},{label:'24 hours',seconds:86400},{label:'7 days',seconds:7*86400},{label:'30 days',seconds:30*86400},{label:'1 year',seconds:365*86400}]
const fmt=(v:number|null|undefined,digits=1)=>v==null?'—':v.toLocaleString(undefined,{maximumFractionDigits:digits})
function aq(pm:number|null){if(pm==null)return null; const c=Math.floor(pm*10)/10; const bands=[[0,9,0,50],[9.1,35.4,51,100],[35.5,55.4,101,150],[55.5,125.4,151,200],[125.5,225.4,201,300],[225.5,325.4,301,500]];for(const [lo,hi,a,b]of bands)if(c>=lo&&c<=hi)return Math.round((c-lo)*(b-a)/(hi-lo)+a);return 500}
function category(a:number|null|undefined){return a==null?'Waiting for data':a<=50?'Good':a<=100?'Moderate':a<=150?'Unhealthy for sensitive groups':a<=200?'Unhealthy':a<=300?'Very unhealthy':'Hazardous'}
function relative(ts:number|null|undefined){if(!ts)return 'Not yet';const s=Math.max(0,Date.now()/1000-ts);return s<90?'Just now':s<3600?`${Math.floor(s/60)} min ago`:s<86400?`${Math.floor(s/3600)} hours ago`:`${Math.floor(s/86400)} days ago`}
async function get<T>(path:string,signal?:AbortSignal):Promise<T>{const r=await fetch(path,{signal,cache:'no-store'});if(!r.ok)throw new Error('The server could not load this view.');return r.json()}
function humidex(tempF:number|null,rh:number|null){if(tempF==null||rh==null)return null;const tC=(tempF-32)*5/9;const e=(rh/100)*6.105*Math.exp((17.27*tC)/(237.7+tC));const hC=tC+0.5555*(e-10.0);return (hC*9/5)+32}
function getMetric(obj:any,m:Metric){if(!obj)return null;if(m==='aqi')return obj.aqi??aq(obj.pm25);if(m==='humidex')return humidex(obj.temperature,obj.humidity);return obj[m]}
const EMPTY:HistoryData={points:[],forecasts:[],step:60,stats:{samples:0,temp_min:null,temp_max:null,temp_mean:null,humidity_mean:null,pm_mean:null,pm_max:null,pm_min:null}}
function App(){
 const [tab,setTab]=useState('Overview'),[metric,setMetric]=useState<Metric>('pm25'),[range,setRange]=useState(86400),[custom,setCustom]=useState(false),[startDate,setStartDate]=useState(''),[endDate,setEndDate]=useState(''),[customBounds,setCustomBounds]=useState<[number,number]|null>(null)
 const [latest,setLatest]=useState<Latest|null>(null),[status,setStatus]=useState<Status|null>(null),[history,setHistory]=useState<HistoryData>(EMPTY),[previous,setPrevious]=useState<HistoryData>(EMPTY),[forecast,setForecast]=useState<Forecast[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[tick,setTick]=useState(0),[comparison,setComparison]=useState(false),[showForecast,setShowForecast]=useState(true),[threshold,setThreshold]=useState(''),[details,setDetails]=useState(false),[offline,setOffline]=useState(!navigator.onLine)
 const [environmentMode,setEnvironmentMode]=useState('')
 const [anchor,setAnchor]=useState(Math.ceil(Date.now()/60000)*60)
 const end=customBounds?.[1]??anchor, start=customBounds?.[0]??end-range
 useEffect(()=>{const id=setInterval(()=>{setAnchor(Math.ceil(Date.now()/60000)*60);setTick(t=>t+1)},60000);const on=()=>setOffline(false),off=()=>setOffline(true);window.addEventListener('online',on);window.addEventListener('offline',off);return()=>{clearInterval(id);window.removeEventListener('online',on);window.removeEventListener('offline',off)}},[])
 useEffect(()=>{const ctrl=new AbortController();setLoading(true);setError('');const params=`start=${start}&end=${end}&step=60${environmentMode?`&environment=${environmentMode}`:''}${threshold!==''?`&threshold=${encodeURIComponent(threshold)}`:''}`;
 Promise.all([get<Latest>(`/api/latest${environmentMode?`?environment=${environmentMode}`:''}`,ctrl.signal),get<Status>('/api/status',ctrl.signal),get<HistoryData>(`/api/history?${params}`,ctrl.signal),get<{points:Forecast[]}>('/api/forecast',ctrl.signal),comparison?get<HistoryData>(`/api/history?start=${Math.max(0,start-(end-start))}&end=${start}&step=60${environmentMode?`&environment=${environmentMode}`:''}`,ctrl.signal):Promise.resolve(EMPTY)])
 .then(([l,s,h,f,p])=>{setLatest(l);setStatus(s);setHistory(h);setForecast(f.points);setPrevious(p)})
 .catch(e=>{if(e.name!=='AbortError')setError('Unable to refresh. Check your Tailscale connection; displayed readings may be out of date.')}).finally(()=>{if(!ctrl.signal.aborted)setLoading(false)});return()=>ctrl.abort()},[start,end,tick,comparison,threshold,environmentMode])
 const tz=status?.timezone??'America/Los_Angeles'
 const time=(ts:number,full=false)=>new Date(ts*1000).toLocaleString(undefined,{timeZone:tz,...(full?{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}:{hour:'numeric',minute:'2-digit'})})
 const date=(ts:number)=>new Date(ts*1000).toLocaleDateString(undefined,{timeZone:tz,month:'short',day:'numeric',year:'numeric'})
 const reading=latest?.reading, meta=metrics[metric],currentAqi=latest?.nowcast_aqi??reading?.aqi
 const currentForecast:any={}
 for(const f of forecast.filter(f=>f.valid===Math.floor((reading?.ts??Date.now()/1000)/3600)*3600)){for(const k of ['temperature','humidity','pm25'] as const)if(f[k]!=null)currentForecast[k]=f[k];if(f.pm25!=null)currentForecast.aqi=aq(f.pm25)}
 const maxUv = forecast.length ? Math.max(...forecast.map(f=>f.uv_index||0)) : 0
 const maxPrecip = forecast.length ? Math.max(...forecast.map(f=>f.precipitation_probability||0)) : 0
 const chart=useMemo(()=>{
  const map=new Map<number,Record<string,number|null>>();const step=history.step
  const getRow=(t:number)=>{const ts=Math.floor(t/step)*step;if(!map.has(ts))map.set(ts,{ts,sensor:null,forecast:null,previous:null});return map.get(ts)!}
  for(let t=Math.floor(start/step)*step;t<end;t+=step)getRow(t)
  for(const p of history.points)getRow(p.ts).sensor=getMetric(p,metric)
  if(showForecast){const grouped=new Map<number,number[]>();for(const f of history.forecasts){const v=getMetric(f,metric);if(v!=null){const t=Math.floor(f.valid/step)*step;grouped.set(t,[...(grouped.get(t)??[]),v])}}for(const[t,vs]of grouped)getRow(t).forecast=vs.reduce((a,b)=>a+b,0)/vs.length}
  if(comparison)for(const p of previous.points)getRow(p.ts+end-start).previous=getMetric(p,metric)
  return [...map.values()].sort((a,b)=>a.ts!-b.ts!)
 },[history,previous,metric,showForecast,comparison,start,end])
 const forecastChart=useMemo(()=>{const map=new Map<number,Record<string,number|null>>();for(const f of forecast){if(!map.has(f.valid))map.set(f.valid,{ts:f.valid,value:null});const v=getMetric(f,metric);if(v!=null)map.get(f.valid)!.value=v}return [...map.values()].sort((a,b)=>a.ts!-b.ts!)},[forecast,metric])
 const hourly=useMemo(()=>{const values:Array<number[]> =Array.from({length:24},()=>[]);for(const p of history.points){const v=getMetric(p,metric);if(v!=null){const hour=Number(new Intl.DateTimeFormat('en-US',{timeZone:tz,hour:'numeric',hourCycle:'h23'}).format(new Date(p.ts*1000)));values[hour].push(v!)}}return values.map((vs,h)=>({hour:`${h.toString().padStart(2,'0')}:00`,value:vs.length?vs.reduce((a,b)=>a+b,0)/vs.length:null}))},[history,metric,tz])
 const stats=history.stats,coverage=Math.min(100,stats.samples/Math.max(1,(Math.min(end,Date.now()/1000)-start)/60)*100)
 const hasData=history.points.length>0
 function applyCustom(){const s=Date.parse(startDate)/1000,e=Date.parse(endDate)/1000;if(!Number.isFinite(s)||!Number.isFinite(e)||e<=s){setError('Choose an end date after the start date.');return}setCustomBounds([s,e])}
 function selectRange(seconds:number){setRange(seconds);setCustomBounds(null);setCustom(false)}
 return <div className="shell">
  <aside className="sidebar"><a className="brand" href="/" aria-label="Indigo home"><span className="brand-mark"><Waves size={24}/></span><span>indigo<span className="brand-dot">.</span></span></a><div className="workspace"><span className="status-dot"/> PERSONAL OBSERVATORY</div>
  <nav>{[{name:'Overview',icon:LayoutDashboard},{name:'History',icon:History},{name:'System',icon:Settings2}].map(({name,icon:Icon})=><button key={name} className={tab===name?'nav active':'nav'} onClick={()=>setTab(name)}><Icon size={18}/>{name}{tab===name&&<ChevronRight size={15}/>}</button>)}</nav>
  <div className="sidebar-note"><div className="orbit"><Wind size={27}/></div><h3>Local monitoring</h3><p>Air quality and weather.</p></div><div className="private"><ShieldCheck size={16}/><div>Private by design<small>Hosted on your homelab</small></div></div></aside>
  <main><header className="topbar"><span>YOUR ENVIRONMENT <ChevronRight size={12}/> {tab.toUpperCase()}</span><div className="top-actions"><span className={'live '+(latest?.stale||error||offline?'warning':'')}><i/>{offline?'Offline':error?'Connection lost':!latest?'Loading':latest.stale?'Awaiting sensor':'Collecting every minute'}</span><button className="icon-button" onClick={()=>setTick(t=>t+1)} aria-label="Refresh readings"><RefreshCw size={16} className={loading?'spinning':''}/></button></div></header>
  <section className="page-heading"><div><span className="eyebrow">{tab==='System'?'SYSTEM':'DASHBOARD'}</span><h1>{tab==='Overview'?'Overview':tab==='History'?'History':'Settings'}</h1><p>{tab==='System'?'Manage database, background jobs, and application settings.':'Current local readings and regional forecasts.'}</p></div><div className="heading-date"><CalendarDays size={16}/>{date(Date.now()/1000)}</div></section>
  {(error||offline)&&<div className="notice">{offline?'You’re offline. Reconnect to your tailnet for fresh readings.':error}</div>}
  {latest?.stale&&!error&&<div className="notice">{reading?`Sensor readings are stale. Last received ${time(reading.ts,true)}.`:'Waiting for the first sensor reading. The collector will retry automatically.'}</div>}
  {tab==='System'?<><section className="system-grid"><article className="panel"><h2><Database size={19}/> Persistent storage</h2><div className="system-value">{fmt((status?.database_bytes??0)/1048576)} <small>MB</small></div><p>{fmt(status?.readings.n,0)} minute records · SQLite WAL</p><dl><dt>First reading</dt><dd>{status?.readings.first?time(status.readings.first,true):'Not yet'}</dd><dt>Last reading</dt><dd>{relative(status?.readings.last)}</dd><dt>Application</dt><dd>v{status?.version??'0.1.2'}</dd></dl></article><article className="panel"><h2><ShieldCheck size={19}/> Backups & access</h2><p className="body-copy">Daily consistent database snapshots are kept on the persistent volume. The latest 14 snapshots are retained.</p><div className="notice">{status?.backup_scope??'Off-server backup is not configured.'}</div><p className="muted">Private access is managed by your tailnet. Address and coordinates are never included in the dashboard API.</p></article></section><section className="panel"><div className="panel-heading"><h2>Collection health</h2><span className="pill">Automatic retries</span></div><div className="job-list">{status?.jobs.map(j=><div className="job" key={j.name}><span className={'job-icon '+(j.error?'bad':'')}><Activity size={18}/></span><div><strong>{j.name==='sensor'?'PurpleAir collector':j.name==='weather'?'Weather & air forecasts':j.name==='backup'?'Daily backup':'Database maintenance'}</strong><p>{j.error??'Running normally'}</p></div><span>{relative(j.last_success)}</span></div>)}</div></section><section className="panel"><div className="panel-heading"><h2>System Settings</h2></div><SystemSettings/></section></>:<>
  {tab==='Overview'&&<section className="metric-grid">{(Object.keys(metrics) as Metric[]).map(key=>{const m=metrics[key],Icon=m.icon;const value=key==='aqi'?currentAqi:getMetric(reading,key);const predicted=getMetric(currentForecast,key);return <button key={key} className={'metric-card '+(metric===key?'selected':'')} onClick={()=>setMetric(key)} style={{'--accent':m.color} as React.CSSProperties}><div className="metric-top"><span>{m.title}</span><Icon size={19}/></div><div className="metric-value">{fmt(value,key==='aqi'?0:1)}{key==='aqi'&&(latest?.nowcast_beyond_scale||reading?.beyond_scale)?'+':''}<small>{m.unit}</small></div><div className="metric-foot">{key==='pm25'?<><span className="tiny-dot"/> {reading?.method==='epa2021'?'EPA 2021 correction':'Raw CF=1 average'}</>:key==='aqi'?<>{category(value)} · {latest?.nowcast_aqi!=null?'NowCast':'interval estimate'}</>:key==='temperature'?`${reading?.environment_mode==='raw'?'Operating sensor':'Estimated ambient'} · raw ${fmt(reading?.temperature_raw)}°F`:`Derived from ${fmt(reading?.temperature)}°F & ${fmt(reading?.humidity)}%`}</div>{predicted!=null&&<div className="forecast-delta">Regional model {fmt(predicted,key==='aqi'?0:1)} {m.unit}{value!=null&&key!=='aqi'&&<span> · {value-predicted>=0?'+':''}{fmt(value-predicted)}</span>}</div>}</button>})}</section>}
  <section className="panel history-panel"><div className="panel-heading"><div><span className="eyebrow">HISTORY</span><h2>{meta.title} over time <span className="unit-label">{meta.unit}</span></h2></div><div className="range-group">{ranges.map(r=><button className={!customBounds&&range===r.seconds?'chosen':''} key={r.seconds} onClick={()=>selectRange(r.seconds)}>{r.label}</button>)}<button className={custom?'chosen':''} onClick={()=>setCustom(!custom)} aria-label="Choose custom dates"><CalendarDays size={15}/></button></div></div>
   {custom&&<div className="custom-dates"><label>From <input type="datetime-local" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><label>To <input type="datetime-local" value={endDate} onChange={e=>setEndDate(e.target.value)}/></label><button className="secondary" onClick={applyCustom}>Apply dates</button><small>Entered in this device’s timezone.</small></div>}
   <div className="chart-navigation"><button aria-label="Previous time window" onClick={()=>setCustomBounds([Math.max(0,start-(end-start)),start])}><ChevronLeft size={15}/></button><span>{date(start)} – {date(end)}</span><button aria-label="Next time window" disabled={end>=Date.now()/1000} onClick={()=>setCustomBounds([end,end+(end-start)])}><ChevronRight size={15}/></button><button aria-label="Zoom in" disabled={end-start<=3600} onClick={()=>setCustomBounds([Math.floor(start+(end-start)/4),Math.floor(end-(end-start)/4)])}><ZoomIn size={15}/></button><button aria-label="Zoom out" disabled={end-start>=365*86400} onClick={()=>setCustomBounds([Math.max(0,Math.floor(start-(end-start)/2)),Math.floor(end+(end-start)/2)])}><ZoomOut size={15}/></button><button onClick={()=>selectRange(86400)}>Live</button></div><div className="chart-toolbar"><div className="legend"><span><i style={{background:meta.color}}/>Your sensor</span>{history.forecasts.length>0&&<label><input type="checkbox" checked={showForecast} onChange={e=>setShowForecast(e.target.checked)}/>Regional forecast</label>}<label><input type="checkbox" checked={comparison} onChange={e=>setComparison(e.target.checked)}/>Previous period</label></div><span className="muted small">{history.step<3600?`${history.step/60} min`:`${history.step/3600} hour`} intervals · {tz.split('/').pop()?.replaceAll('_',' ')}</span></div>
   <div className="main-chart">{hasData?<ResponsiveContainer width="100%" height="100%"><ComposedChart data={chart} margin={{top:14,right:8,bottom:0,left:-22}}><defs><linearGradient id="chartFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={meta.color} stopOpacity={.2}/><stop offset="100%" stopColor={meta.color} stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#26313e" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="ts" type="number" domain={[start,end]} tickFormatter={t=>end-start>172800?new Date(t*1000).toLocaleDateString(undefined,{timeZone:tz,month:'short',day:'numeric'}):time(t)} stroke="#7d8a9a" tickLine={false} axisLine={false} minTickGap={60}/><YAxis stroke="#7d8a9a" tickLine={false} axisLine={false} domain={metric==='temperature'?['auto','auto']:[0,'auto']}/><Tooltip contentStyle={{background:'#1a2533',border:'1px solid #3c4c60',borderRadius:12}} labelFormatter={v=>time(Number(v),true)} formatter={(v)=>[fmt(Number(v)),undefined]}/><Area type="linear" dataKey="sensor" name="Your sensor" stroke={meta.color} fill="url(#chartFill)" strokeWidth={2} dot={{r:1.8,strokeWidth:0}} activeDot={{r:4}} connectNulls={false} isAnimationActive={false}/><Line type="linear" dataKey="forecast" name="Regional forecast" stroke="#99a7bd" strokeDasharray="5 5" strokeWidth={1.5} dot={false} connectNulls isAnimationActive={false}/><Line dataKey="previous" name="Previous period" stroke="#8876bd" strokeWidth={1.3} dot={false} connectNulls={false} isAnimationActive={false}/></ComposedChart></ResponsiveContainer>:<div className="empty-chart"><Waves size={42}/><h3>{loading?'Loading...':'No data available.'}</h3><p>Readings will appear as your sensor reports. Choose another date range to explore earlier data.</p></div>}</div>
   <div className="chart-bottom"><span><Clock3 size={14}/>{stats.samples.toLocaleString()} readings in this window</span>{tab==='Overview'?<button onClick={()=>{setTab('History');window.scrollTo({top:0,behavior:'smooth'})}}>View full history <ArrowUpRight size={14}/></button>:<button onClick={()=>{document.getElementById('explore-readings')?.scrollIntoView({behavior:'smooth'})}}>Inspect readings <ArrowDownToLine size={14}/></button>}</div>
  </section>
  {tab==='Overview'&&<section className="lower-grid"><article className="panel"><div className="panel-heading"><div><span className="eyebrow">FORECAST</span><h2>The next 72 hours</h2></div><span className="pill">Forecast</span></div><p className="muted">Regional {metric==='aqi'?'US AQI':meta.title.toLowerCase()} · {meta.unit}</p><div className="mini-chart">{forecastChart.some(p=>p.value!=null)?<ResponsiveContainer width="100%" height="100%"><ComposedChart data={forecastChart} margin={{left:-28,right:4,top:8}}><CartesianGrid stroke="#26313e" vertical={false}/><XAxis dataKey="ts" tickFormatter={t=>new Date(t*1000).toLocaleDateString(undefined,{timeZone:tz,weekday:'short'})} minTickGap={85} axisLine={false} tickLine={false} stroke="#7d8a9a"/><YAxis axisLine={false} tickLine={false} stroke="#7d8a9a" domain={['auto','auto']}/><Tooltip contentStyle={{background:'#1a2533',border:'1px solid #3c4c60'}} labelFormatter={v=>time(Number(v),true)} formatter={v=>[fmt(Number(v)),meta.unit]}/><Line dataKey="value" stroke={meta.color} dot={false} strokeWidth={2}/></ComposedChart></ResponsiveContainer>:<div className="empty-small">Forecasts will appear after location setup and the next successful refresh.</div>}</div><div className="stat-row"><span>Peak UV Index</span><strong>{fmt(maxUv)}</strong></div><div className="stat-row"><span>Peak Precipitation Prob.</span><strong>{fmt(maxPrecip)}<small>%</small></strong></div><p className="source">Refreshed {relative(forecast.length?Math.max(...forecast.map(f=>f.fetched)):null)}. Model estimates, not measurements at your home. <a href="https://open-meteo.com/" target="_blank" rel="noreferrer">Open-Meteo</a> · <a href="https://atmosphere.copernicus.eu/" target="_blank" rel="noreferrer">CAMS</a></p></article>
  <article className="panel summary-panel"><span className="eyebrow">SUMMARY</span><h2>Statistics</h2><div className="stat-row"><span>Average PM2.5</span><strong>{fmt(stats.pm_mean)} <small>µg/m³</small></strong></div><div className="stat-row"><span>Peak PM2.5</span><strong>{fmt(stats.pm_max)} <small>µg/m³</small></strong></div><div className="stat-row"><span>Temperature range</span><strong>{fmt(stats.temp_min)}–{fmt(stats.temp_max)} <small>°F</small></strong></div><div className="stat-row"><span>Collection coverage</span><strong>{fmt(coverage,1)}<small>%</small></strong></div><div className="coverage"><i style={{width:coverage+'%'}}/></div><p className="muted small">Coverage includes time before collection began. Missing samples stay visible as gaps.</p></article></section>}
  {(tab==='History'||details)&&<><section className="panel"><div className="panel-heading"><div><span className="eyebrow">HOURLY AVERAGE</span><h2>Average by hour of day</h2></div><span className="pill">{meta.unit}</span></div><div className="mini-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={hourly} margin={{left:-25}}><XAxis dataKey="hour" interval={3} stroke="#7d8a9a" axisLine={false} tickLine={false}/><YAxis stroke="#7d8a9a" axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:'#1a2533',border:'1px solid #3c4c60'}} formatter={v=>[fmt(Number(v)),meta.unit]}/><Bar dataKey="value" fill={meta.color} radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></div><p className="muted small">Mean of displayed intervals, grouped by local hour. Use shorter ranges for finer detail.</p></section><section className="panel" id="explore-readings"><div className="panel-heading"><h2>Explore readings</h2><a className="secondary" href={`/api/export?start=${start}&end=${end}`}><ArrowDownToLine size={15}/> Export all minutes</a></div><div className="filter"><label>Highlight PM2.5 at or above <input type="number" min="0" placeholder="e.g. 35.5" value={threshold} onChange={e=>setThreshold(e.target.value)}/> µg/m³</label></div><div className="table-scroll"><table><thead><tr><th>Time</th><th>PM2.5</th><th>AQI estimate</th><th>Temperature</th><th>Humidity</th><th>Samples</th></tr></thead><tbody>{[...history.points].reverse().filter(p=>threshold===''||p.above_threshold).slice(0,100).map(p=><tr key={p.ts} className={p.above_threshold?'highlight':''}><td>{time(p.ts,true)}{p.flagged>0&&<span title="One or more samples has a quality flag"> *</span>}</td><td>{fmt(p.pm25)}</td><td>{fmt(p.aqi,0)}</td><td>{fmt(p.temperature)}°F</td><td>{fmt(p.humidity)}%</td><td>{p.samples}</td></tr>)}</tbody></table></div><p className="muted small">Showing up to 100 recent intervals matching the filter. CSV includes every minute in the selected range. * Channel quality flag.</p></section></>}
  <div className="environment-choice"><label>Temperature &amp; humidity view <select value={environmentMode||reading?.environment_mode||'purpleair'} onChange={e=>setEnvironmentMode(e.target.value)}><option value="purpleair">PurpleAir estimated ambient</option><option value="raw">Raw operating readings</option><option value="simple">Simple correction</option></select></label></div><section className="method-note"><CircleHelp size={17}/><p>PM2.5 {reading?.method==='epa2021'?'uses the EPA 2021 correction (not the extended wildfire formula).':'shows the raw CF=1 channel average.'} US AQI uses EPA 2024 breakpoints. NowCast appears after at least two of the latest three completed hours have 45 valid samples each; otherwise the current AQI is an interval estimate. Historical AQI is calculated from each interval’s mean PM2.5. Temperature and humidity use the selected view; raw operating readings remain stored. Estimated ambient values use PurpleAir’s Wallace formulas, while simple correction uses −8°F and +4 humidity points. PM2.5 correction always uses raw humidity.{reading?.quality&&` Latest quality flag: ${reading.quality.replaceAll('_',' ')}.`}</p></section></>}
  <footer><span><Waves size={15}/> INDIGO STATS</span><span><span className="footer-dot">·</span> {reading?`Updated ${relative(reading.ts)}`:'Awaiting first reading'}</span><span><Check size={13}/> Stored on your homelab</span></footer>
  </main></div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
